# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['web_ui.py'],
    pathex=['.'],
    binaries=[
        ('temp_nodejs/nodejs/node.exe', 'nodejs/'),
    ],
    datas=[
        ('frontend/dist', 'frontend/dist'),
        ('templates', 'templates'),
        ('static', 'static'), 
        ('translate_helper', 'translate_helper'),
        ('api', 'api'),
        ('temp_nodejs/nodejs', 'nodejs/'),
        ('models', 'models'),
    ],
    hiddenimports=[
        'flask',
        'werkzeug',
        'jinja2',
        'click',
        'itsdangerous',
        'markupsafe',
        'openai',
        'anthropic',
        'requests',
        'urllib3',
        'certifi',
        'charset_normalizer',
        'idna',
        'argparse',
        'logging',
        'json',
        'os',
        'sys',
        'threading',
        'queue',
        'time',
        'datetime',
        'hashlib',
        'uuid',
        'subprocess',
        'tempfile',
        'shutil',
        'zipfile',
        're',
        # ChromaDB相关依赖
        'chromadb',
        'chromadb.api',
        'chromadb.config',
        'chromadb.db',
        'chromadb.db.impl',
        'chromadb.db.impl.sqlite',
        'chromadb.db.impl.grpc',
        'chromadb.utils',
        'chromadb.telemetry',
        'sqlite3',
        'duckdb',
        'onnxruntime',
        'overrides',
        'posthog',
        'pulsar_client',
        'pydantic',
        'typing_extensions',
        # C扩展模块 - 提高ChromaDB性能
        '_testbuffer',
        '_testcapi',
        '_testimportmultiple',
        '_testinternalcapi',
        '_testmultiphase',
        'array',
        '_array',
        'cmath',
        'math',
        '_datetime',
        '_decimal',
        '_heapq',
        '_bisect',
        '_random',
        '_operator',
        '_collections',
        '_functools',
        '_pickle',
        '_json',
        '_struct',
        '_csv',
        '_sqlite3',
        '_lzma',
        '_bz2',
        'zlib',
        '_hashlib',
        '_md5',
        '_sha1',
        '_sha256',
        '_sha512',
        '_blake2',
        '_sha3',
        'api.config_api',
        'api.translation_api', 
        'api.progress_api',
        'api.terminology_api',
        'api.review_api',
        'api.memory_api',
        'translate_helper.translate_helper_base',
        'translate_helper.translate_helper_csv',
        'translate_helper.translate_helper_jar',
        'translate_helper.translate_helper_json',
        'config_manager',
        'global_values',
        'improved_translator',
        'progress_manager',
        'translation_object',
        'vector_translation_memory',
        'model_manager',
    ],
    hookspath=['.'],
    runtime_hooks=[],
    excludes=[
        'configs',
        'translation_work',
        'vector_memory',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=None,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=None)

exe = EXE(
    pyz,
    a.scripts, 
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='StarsectorTranslator',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    runtime_tmpdir=None,
    console=True,
    argv_emulation=False,
)
